### ISSUE TITLE
[P2] Correct unverified role permissions

### ISSUE THREAD

**Issue by lyonva** [lyonva/ClassMateBot#7]
When created by the bot, the unverified role should block a user from seeing/participating in any channel except "#general" until they use the $verify command. As of now this is not always the case - need to fix permissions/role weight to ensure this.

**Comment by Capt-Fluffy-Bug** [comment]
Fixed unverified member permission issues.

**Comment by ConnorS1110** [comment]
Permissions are not correctly implemented
